# Generated by Django 3.1.3 on 2021-02-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210215_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderTotal',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=7),
            preserve_default=False,
        ),
    ]
