# Generated by Django 3.1.3 on 2021-02-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_ordertotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderTotal',
        ),
    ]
