# Generated by Django 3.1.3 on 2021-06-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='count_views',
            field=models.BigIntegerField(default=0, max_length=7),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
