# Generated by Django 3.1.3 on 2021-06-12 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210613_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='count_views',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
