# Generated by Django 3.1.3 on 2021-06-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210613_0131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductDetails',
            new_name='Details',
        ),
    ]
